応用編（シングルページレイアウト）index.htmlを作成しました。
mioyamamoto/training.frontend pull request #11
Opened 2017-04-24 06:06 UTC by mio-yamamoto

ベースとなるHTMLを記述しました。

2017-04-24 06:42 UTC, gkoyama requested changes
コメントしました。
あと、バリデーションをかけましょう。

2017-04-24 06:42 UTC, gkoyama commented on HTML.CSS/02.Advanced/シングルページレイアウト/index.html
> +   <meta http-equiv="X-UA-Compatible" content="IE=edge">
質問ですが、これいりますか？

2017-04-24 06:42 UTC, gkoyama commented on HTML.CSS/02.Advanced/シングルページレイアウト/index.html
> +            <p><input type="text" value="NAME"></p>
formの中＜ｐ＞いる？
あと、inputやtextareaのデフォルトで文言を表示させる方法は他にありますよ

2017-04-24 06:42 UTC, gkoyama commented on HTML.CSS/02.Advanced/シングルページレイアウト/index.html
> +<div class="header-container">
各セクションの直下のdivは何の為につけてますか？

2017-04-24 06:42 UTC, gkoyama commented on HTML.CSS/02.Advanced/シングルページレイアウト/index.html
> +            </li>
敢えてなら良いですが、imgが無いけど大丈夫ですか？

2017-04-24 07:12 UTC, mio-yamamoto commented on HTML.CSS/02.Advanced/シングルページレイアウト/index.html
> +            </li>
imgの配置方法が浮かばなかったので、現状記述できませんでした。
768px以下の時、それぞれの画像はそれぞれの<li>に対して、背景画像として用いられているように見えます。。

2017-04-24 07:15 UTC, mio-yamamoto commented on HTML.CSS/02.Advanced/シングルページレイアウト/index.html
> +            <p><input type="text" value="NAME"></p>
参考書（基礎編）の記法で書いたのですが、いらないですね。。
デフォルトの文字の表示方法は変更できました！

2017-04-24 07:16 UTC, mio-yamamoto commented on HTML.CSS/02.Advanced/シングルページレイアウト/index.html
> +<div class="header-container">
クラス名の記述を`<div>`ではなく、各セクションのタグ内に移しました。

2017-04-24 07:20 UTC, gkoyama commented on HTML.CSS/02.Advanced/シングルページレイアウト/index.html
> +<div class="header-container">
headerもdivいらなそうですね

2017-04-24 07:21 UTC, gkoyama commented on HTML.CSS/02.Advanced/シングルページレイアウト/index.html
> +            </li>
敢えてならそれで進めてみていいですよ！

2017-04-25 09:52 UTC, mio-yamamoto commented
モバイルファーストCSSをやめました。
ひとまず、1200pxで表示されている通りに作ってみようと思います。
フォームのフォントサイズが不明…！

2017-04-28 07:45 UTC, gkoyama requested changes
header - ボタンのマウスオーバーが無い
works - ボタンのマウスオーバーが無い

2017-04-28 08:21 UTC, gkoyama reviewed
確認しました。
OKです！

2017-05-01 10:14 UTC, mio-yamamoto commented
先ほど上げたものを一旦完成版とさせてください。修正点ありましたらご指摘お願いいたします。

2017-05-02 04:47 UTC, gkoyama approved these changes
LGTM!
OKです！

2017-05-02 07:19 UTC, merged