[WIP]基礎編のchapter5（リンクの設定と画像の表示）の途中経過をお送りします。
mioyamamoto/training.frontend pull request #5
Opened 2017-04-11 10:24 UTC by mio-yamamoto

## のこり
- section 4 : 画像にリンクをつける
- section 5 : 画像にテキストを回り込ませる

よろしくお願いします！

2017-04-11 13:12 UTC, gkoyama commented on HTML.CSS/01.Basic/chapter5/chapter5_2d.html
> +            content: url(images/opentab.png);
ここは参考書と違いますが、ルートを理解してあえてこうしてますか？
理解しているならOKです！

2017-04-11 13:26 UTC, gkoyama reviewed
section3まではOKです！
確認ですが、ルートやindex.htmlの記述が違ったり書いてなかったりは理解の上でしょうか？
理解しているならOKです！
よく勉強されていると思います。
引き続きsection4~お願い致します。

2017-04-12 03:55 UTC, mio-yamamoto commented on HTML.CSS/01.Basic/chapter5/chapter5_2d.html
> +            content: url(images/opentab.png);
理解しています！同じディレクトリ（「chapter5」）内に「images」を作成したので、上記のルートに変更しています。

2017-04-12 03:59 UTC, mio-yamamoto commented
ありがとうございます。
自分なりに理解した上で参考書と異なる記述にしていますが、認識が違っていればその都度ご指摘のほどよろしくお願いいたします。。！

2017-04-12 08:23 UTC, mioyamamoto reviewed
残りのファイルを追加しておりますので、ご確認のほどよろしくお願いいたします！

2017-04-12 09:36 UTC, gkoyama requested changes
LGTM!
OKです！
これは指摘ではなく補足ですが、
ウチでは下記のようなルールがあったりするので、その辺も理解しつつ勉強していくといいかもしれませんね！
※これは各会社や案件によって変わる『ルール』ですので、なにが正解というワケではありません。

ガイドライン
http://guideline.leilab.org/
カラーコード
カラーコードは大文字６桁とする。3桁への省略は行わない。
例；
✕
(白) #fff
↓
◯
(白) #FFFFFF

2017-04-12 09:37 UTC, gkoyama approved these changes

2017-04-12 09:46 UTC, mio-yamamoto commented
補足、承知いたしました。ありがとうございます！
ガイドライン、少しずつ確認してみます！

2017-04-12 09:46 UTC, merged